week5/W5D1/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands, only: [:new, :create, :destroy, :update, :show, :index, :edit]
  
end

week5/W5D1/music_app/app/models/band.rb
class Band < ApplicationRecord

  validates :name, presence: true, uniqueness: true

  has_many :albums, dependent: :destroy
  
end

week5/W5D1/music_app/app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  validates :password_digest, presence: true
  validates :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  private
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

end

week5/W5D1/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :logged_in?

  private

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !current_user.nil
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_user!
    redirect_to new_session_url if current_user.nil?
  end

end

week5/W5D1/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_user!

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def band_params
    params.require(:band).permit(:name)
  end

  def update
      @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end


end

week5/W5D1/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    if user.nil?
      flash.now[:errors] = ["Incorrect email and/or password"]
      render :new
    else
      login_user!(user)
      redirect_to user_url(user) #Need to specify the user so it can grab the id.
    end
  end

  def destroy
    logout_user!
    redirect_to new_session_url
  end

  def new
    render :new
  end



end

week5/W5D1/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save!
      login_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def show
    render :show
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

week5/W5D1/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

week5/W5D1/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

week5/W5D1/music_app/app/helpers/users_helper.rb
module UsersHelper
end

week5/W5D1/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
    <h1><%= link_to 'MusicApp', bands_url %></h1>
    <div>
    <% if current_user.nil? %>
      <%= button_to 'Sign in', new_session_url, method: :get %>
      <%= button_to 'Sign up', new_user_url, method: :get %>
    <% else %>
      <%= current_user.email %>
      <%= button_to 'Logout', session_url, method: :delete %>
    <% end %>
    </div>
    </nav>

    <%= yield %>
  </body>
</html>

week5/W5D1/music_app/app/views/users/new.html.erb
<h3>Sign Up!</h3>

<form action="<%= users_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label for='new-user-email'>Email</label>
    <input type="text" name="user[email]">
  </p>

  <p>
    <label for='new-user-password'>Password</label>
    <input type="password" name="user[password]">
  </p>

  <input type="submit" value="Sign-up">
</form>

week5/W5D1/music_app/app/views/users/show.html.erb
<h1>Profile</h1>
<p>
  Your email is: <%= current_user.email %>
</p>